# из-за devtools так как классы из внешних библиотек загружаются из base classloader
# а kafkaListener ищет LinkUpdateAvro в Restart ClassLoader
# (классы созданые разработчиком а именно LinkUpdateAvro в generated-source)
# то мы должны явно указать чтобы оба LinkUpdateAvro были из restart classloader
restart.include.avro=.*avro-[\\d\\.]+\\.jar

restart.include.confluent-avro=.*kafka-avro-serializer-[\\d\\.]+\\.jar
restart.include.confluent-schema=.*kafka-schema-serializer-[\\d\\.]+\\.jar
restart.include.confluent-registry=.*kafka-schema-registry-client-[\\d\\.]+\\.jar
restart.include.confluent-rules=.*kafka-schema-rules-[\\d\\.]+\\.jar

restart.include.confluent-config=.*common-config-[\\d\\.]+\\.jar
restart.include.confluent-utils=.*common-utils-[\\d\\.]+\\.jar
