global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'scrapper'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['scrapper:8012']
        labels:
          application: 'scrapper'

  - job_name: 'bot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bot:8011']
        labels:
          application: 'bot'

  - job_name: 'ai-agent'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ai-agent:8013']
        labels:
          application: 'ai-agent'

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: [ 'pushgateway:9091' ]
