server:
  port: 8081

spring:
  application:
    name: scrapper
  grpc:
    server:
      port: 9081
    client:
      default-channel:
        address: 'static://localhost:9080'
        negotiation-type: plaintext
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
  data:
    redis:
      cluster:
        nodes:
          - 127.0.0.1:7001
          - 127.0.0.1:7002
          - 127.0.0.1:7003
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 10s
app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.stackexchange.com/2.3
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.github.com
    per-page: 50
  bot:
    uri: http://localhost:8080
  scheduler:
    enable: true
    interval: 30s
    batch-size: 100
    thread-count: 4
    max-pages: 100
  communication:
    client:
      mode: kafka # rest, grpc
    controller:
      mode: grpc # rest
  db:
    access-type: ORM
  controller:
    batch-size: 100
  client:
    batch-size: 100
  kafka:
    schema-registry: http://localhost:9093
    topic:
      name: bot-updates-topic
      partitions: 3
      replicas: 3
    send-delay: 60s
    outbox:
      max-retries: 5
      delay: 120s
      max-batches: 10
      batch-send-size: 500
      batch-clean-size: 5000
    min-insync-replicas: 2

  redis:
    time-to-live: 2m
    lettuce:
      client:
        host: 127.0.0.1
    cache-key-prefix: links:byTgChat

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg %clr(%kvp){yellow}%n"
  level:
    root: INFO
