server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: scrapper
  grpc:
    server:
      port: 9081
    client:
      default-channel:
        address: 'static://localhost:9080'
        negotiation-type: plaintext
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
  data:
    redis:
      cluster:
        nodes:
          - 127.0.0.1:7001
          - 127.0.0.1:7002
          - 127.0.0.1:7003
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 10s
app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.stackexchange.com/2.3
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.github.com
    per-page: 50
  bot:
    uri: http://localhost:8080
  scheduler:
    enable: true
    interval: 30s
    batch-size: 100
    thread-count: 4
    max-pages: 100
  communication:
    client:
      mode: kafka # rest, grpc
      connect-timeout: 5s
      read-timeout: 10s
    controller:
      mode: rest # rest
  db:
    access-type: ORM
  controller:
    batch-size: 100
  client:
    batch-size: 100
  kafka:
    schema-registry: http://localhost:9093
    topic:
      name: link.raw-updates
      partitions: 3
      replicas: 3
    send-delay: 60s
    outbox:
      max-retries: 5
      delay: 120s
      max-batches: 10
      batch-send-size: 500
      batch-clean-size: 5000
    min-insync-replicas: 2
    consumers:
      retry:
        attempts: 3
        interval: 3000
      concurrency: 3
      group-id: circuit-breaker-group
      topic:
        chat-reg: chat-registration-topic
        link-add: link-add-topic
        link-remove: link-remove-topic
  redis:
    time-to-live: 2m
    lettuce:
      client:
        host: 127.0.0.1
    cache-key-prefix: links:byTgChat
  rate-limiter:
    api:
      caffeine:
        expire-time: 5m
        size: 10000

resilience4j:
  circuitbreaker:
    instances:
      bot:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 1s
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpClientErrorException.TooManyRequests
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException.BadRequest
          - org.springframework.web.client.HttpClientErrorException.Unauthorized
          - org.springframework.web.client.HttpClientErrorException.Forbidden
          - org.springframework.web.client.HttpClientErrorException.NotFound
          - org.springframework.web.client.HttpClientErrorException.Conflict
          - backend.academy.linktracker.scrapper.client.bot.BotClientException
      external:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 1s
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpClientErrorException.TooManyRequests
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException.BadRequest
          - org.springframework.web.client.HttpClientErrorException.Unauthorized
          - org.springframework.web.client.HttpClientErrorException.Forbidden
          - org.springframework.web.client.HttpClientErrorException.NotFound
          - org.springframework.web.client.HttpClientErrorException.Conflict
          - backend.academy.linktracker.scrapper.client.StackOverflowException
          - backend.academy.linktracker.scrapper.client.GitHubClientException
    circuit-breaker-aspect-order: 398

  retry:
    instances:
      bot:
        max-attempts: 3
        wait-duration: 3s
        enable-randomized-wait: false
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - backend.academy.linktracker.scrapper.client.bot.BotClientException
      bot-exponent:
        max-attempts: 3
        wait-duration: 3s
        enable-randomized-wait: true
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - backend.academy.linktracker.scrapper.client.bot.BotClientException
      external:
        max-attempts: 5
        wait-duration: 3s
        enable-randomized-wait: false
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
      external-exponent:
        max-attempts: 5
        wait-duration: 3s
        enable-randomized-wait: true
        exponential-backoff-multiplier: 2
        enable-exponential-backoff: true
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
    retry-aspect-order: 399

  ratelimiter:
    instances:
      bot:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 5s
      api:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 5s
    rate-limiter-aspect-order: 397
    configs:
      api:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 5s
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg %clr(%kvp){yellow}%n"
  level:
    root: INFO

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
      path-mapping:
        prometheus: metrics
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    export:
      prometheus:
        enabled: true
        pushgateway:
              enabled: true
              base-url: http://localhost:9091
              push-rate: 30s
              job: ${spring.application.name}
