apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'pushgateway'
        static_configs:
          - targets: ['pushgateway-svc:9091']

      - job_name: 'scrapper'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['scrapper-svc:8081']

      - job_name: 'bot'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['bot-svc:8080']

      - job_name: 'kafka'
        static_configs:
          - targets:
              - 'kafka-0.kafka-hs:9092'
              - 'kafka-1.kafka-hs:9092'
              - 'kafka-2.kafka-hs:9092'
