apiVersion: v1
kind: Service
metadata:
  name: valkey-hs
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: valkey
  selector:
    app: valkey
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-cluster
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: valkey
  selector:
    app: valkey
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
spec:
  serviceName: valkey-hs
  replicas: 6
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:latest
          command:
            - valkey-server
          args:
            - "--port"
            - "6379"
            - "--cluster-enabled"
            - "yes"
            - "--cluster-config-file"
            - "/data/nodes.conf"
            - "--cluster-node-timeout"
            - "5000"
            - "--appendonly"
            - "yes"
            - "--dir"
            - "/data"
            - "--protected-mode"
            - "no"
            - "--bind"
            - "0.0.0.0"
          ports:
            - containerPort: 6379
              name: valkey
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
