openapi: 3.1.0
info:
  title: OpenAPI definition
  version: 1.0.0
servers:
  - url: /api/v1
    description: Scrapper API v1
paths:
  /subscriptions:
    get:
      summary: Получить список подписок по необязательным параметрам с пагинацией
      operationId: getSubscriptions
      tags:
        - subscriptions
      parameters:
        - name: tag
          in: query
          required: false
          schema:
            type: string
        - name: urlContains
          in: query
          required: false
          schema:
            type: string
        - name: lastCheckBefore
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: lastCheckAfter
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: chatId
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
            default: 0
            example: 0
        - name: size
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
            example: 20
        - name: sort
          in: query
          required: true
          style: form
          schema:
            type: string
            example: "lastCheckedAt,desc"
      responses:
        '200':
          description: Список подписок успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageSubscriptionsResponse'
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /chats:
    get:
      summary: Получить список чатов с пагинацией и количеством активных ссылок
      operationId: getChats
      tags:
        - chats
      x-spring-paginated: true
      responses:
        '200':
          description: Список чатов успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatsPageResponse'
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /tg-chat/{id}:
    get:
      summary: Получить чат со списком ссылок
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Чат и ссылки получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatAndListLinksResponse'
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '404':
          description: Чат не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    post:
      summary: Зарегистрировать чат
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Чат зарегистрирован
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '409':
          description: Чат уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    delete:
      summary: Удалить чат
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Чат успешно удалён
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '404':
          description: Чат не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /links:
    get:
      summary: Получить все отслеживаемые ссылки
      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: tag
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Ссылки успешно получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLinksResponse'
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '404':
          description: Ссылка не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    post:
      summary: Добавить отслеживание ссылки
      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddLinkRequest'
        required: true
      responses:
        '200':
          description: Ссылка успешно добавлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '404':
          description: Чат не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '409':
          description: Ссылка уже отслеживается
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    delete:
      summary: Убрать отслеживание ссылки
      parameters:
        - name: Tg-Chat-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveLinkRequest'
        required: true
      responses:
        '200':
          description: Ссылка успешно убрана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '404':
          description: Чат не существует или ссылка не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorCode:
      type: string
      enum:
        - CHAT_NOT_FOUND
        - LINK_NOT_FOUND
        - LINK_ALREADY_EXISTS
        - INVALID_REQUEST
        - CHAT_ALREADY_EXISTS
        - INTERNAL_ERROR
    LinkResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
          format: uri
        tags:
          type: array
          items:
            type: string
        lastCheckedAt:
          type: string
          format: date-time
    SubscriptionResponse:
      type: object
      properties:
        chatId:
          type: integer
          format: int64
        linkId:
          type: integer
          format: int64
        tags:
          type: array
          items:
            type: string
        url:
          type: string
          format: uri
        lastCheckedAt:
          type: string
          format: date-time
    ApiErrorResponse:
      type: object
      required:
        - errorCode
        - errorDescription
        - statusCode
      properties:
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        errorDescription:
          type: string
        statusCode:
          type: integer
    PageSubscriptionsResponse:
      type: object
      properties:
        subscriptions:
          type: array
          items:
            $ref: '#/components/schemas/SubscriptionResponse'
        totalPages:
          type: integer
        totalElements:
          type: integer
          format: int64
        number:
          type: integer
          description: Номер текущей страницы (начиная с 0)
        size:
          type: integer
          description: Размер страницы
        numberOfElements:
          type: integer
          description: Количество элементов на текущей странице
        first:
          type: boolean
        last:
          type: boolean
        empty:
          type: boolean
    AddLinkRequest:
      type: object
      properties:
        link:
          type: string
          format: uri
        tags:
          type: array
          items:
            type: string
        filters:
          type: array
          items:
            type: string
    ListLinksResponse:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkResponse'
        size:
          type: integer
          format: int32
    RemoveLinkRequest:
      type: object
      properties:
        link:
          type: string
          format: uri
    ChatAndListLinksResponse:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkResponse'
        chatId:
          type: integer
          format: int64
    ChatSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор чата
        activeLinksCount:
          type: integer
          format: int64
          description: Количество активных ссылок в этом чате
    ChatsPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ChatSummary'
        totalPages:
          type: integer
        totalElements:
          type: integer
          format: int64
        number:
          type: integer
          description: Номер текущей страницы (начиная с 0)
        size:
          type: integer
          description: Размер страницы
        numberOfElements:
          type: integer
          description: Количество элементов на текущей странице
        first:
          type: boolean
        last:
          type: boolean
        empty:
          type: boolean
security:
  - bearerAuth: []
