apiVersion: apps/v1
kind: Deployment
metadata:
  name: linktracker-ai-agent
spec:
  selector:
    matchLabels:
      app: linktracker-ai-agent
  template:
    metadata:
      labels:
        app: linktracker-ai-agent
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres-db-svc 5432; do echo waiting for postgres; sleep 2; done']
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka-0.kafka-hs 9092; do echo waiting for kafka; sleep 2; done']
      containers:
        - name: linktracker-ai-agent
          image: linktracker/ai-agent:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
            - containerPort: 8013
              name: management
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: app-config
            - name: YANDEXGPT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: linktracker-secrets
                  key: YANDEXGPT_API_KEY
            - name: YANDEXGPT_FOLDER_ID
              valueFrom:
                secretKeyRef:
                  name: linktracker-secrets
                  key: YANDEXGPT_FOLDER_ID
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: linktracker-ai-agent-external
  labels:
    app: linktracker-ai-agent
spec:
  type: NodePort
  selector:
    app: linktracker-ai-agent
  ports:
    - port: 8082
      targetPort  : 8082
      nodePort: 30082
      name: http
    - port: 8013
      targetPort  : 8013
      nodePort: 30013
      name: management
